package de.kreth.clubhelper.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import de.kreth.clubhelper.PersonType;
import de.kreth.clubhelper.dao.PersonDao;
import de.kreth.clubhelper.dao.ContactDao;
import de.kreth.clubhelper.dao.AttendanceDao;
import de.kreth.clubhelper.dao.AdressDao;
import de.kreth.clubhelper.dao.RelativeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 4): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 4;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        PersonDao.createTable(db, ifNotExists);
        ContactDao.createTable(db, ifNotExists);
        AttendanceDao.createTable(db, ifNotExists);
        AdressDao.createTable(db, ifNotExists);
        RelativeDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        PersonDao.dropTable(db, ifExists);
        ContactDao.dropTable(db, ifExists);
        AttendanceDao.dropTable(db, ifExists);
        AdressDao.dropTable(db, ifExists);
        RelativeDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            for(int migrateVersion = oldVersion+1; migrateVersion<=newVersion; migrateVersion++)
                upgrade(db, migrateVersion);
            onCreate(db);
        }

        private void upgrade(SQLiteDatabase db, int migrateVersion) {
            switch (migrateVersion) {
                case 4:
                    try {
                        db.beginTransaction();
                        Date created = new GregorianCalendar(2000, Calendar.JANUARY, 1).getTime();
                        Date changed = new Date();

                        db.execSQL("ALTER TABLE " + PersonDao.TABLENAME + " ADD COLUMN 'CHANGED' INTEGER NOT NULL");
                        db.execSQL("ALTER TABLE " + PersonDao.TABLENAME + " ADD COLUMN 'CREATED' INTEGER NOT NULL");

                        db.execSQL("ALTER TABLE " + ContactDao.TABLENAME + " ADD COLUMN 'CHANGED' INTEGER NOT NULL");
                        db.execSQL("ALTER TABLE " + ContactDao.TABLENAME + " ADD COLUMN 'CREATED' INTEGER NOT NULL");

                        db.execSQL("ALTER TABLE " + RelativeDao.TABLENAME + " ADD COLUMN 'CHANGED' INTEGER NOT NULL");
                        db.execSQL("ALTER TABLE " + RelativeDao.TABLENAME + " ADD COLUMN 'CREATED' INTEGER NOT NULL");

                        db.execSQL("ALTER TABLE " + AdressDao.TABLENAME + " ADD COLUMN 'CHANGED' INTEGER NOT NULL");
                        db.execSQL("ALTER TABLE " + AdressDao.TABLENAME + " ADD COLUMN 'CREATED' INTEGER NOT NULL");

                        db.execSQL("ALTER TABLE " + AttendanceDao.TABLENAME + " ADD COLUMN 'CHANGED' INTEGER NOT NULL");
                        db.execSQL("ALTER TABLE " + AttendanceDao.TABLENAME + " ADD COLUMN 'CREATED' INTEGER NOT NULL");


                        db.execSQL("UPDATE " + PersonDao.TABLENAME + " SET " +
                                PersonDao.Properties.Type.columnName + "='" + PersonType.ACTIVE.name() + "' " +
                                "WHERE " + PersonDao.Properties.Type.columnName + "='ACITVE'");

                        db.execSQL("UPDATE " + PersonDao.TABLENAME + " SET " +
                                PersonDao.Properties.Changed.columnName + "='" + changed.getTime() + ", " +
                                PersonDao.Properties.Created.columnName + "=" + created.getTime() + " ");

                        db.execSQL("UPDATE " + ContactDao.TABLENAME + " SET " +
                                ContactDao.Properties.Changed.columnName + "='" + changed.getTime() + ", " +
                                ContactDao.Properties.Created.columnName + "=" + created.getTime() + " ");

                        db.execSQL("UPDATE " + RelativeDao.TABLENAME + " SET " +
                                RelativeDao.Properties.Changed.columnName + "='" + changed.getTime() + ", " +
                                RelativeDao.Properties.Created.columnName + "=" + created.getTime() + " ");

                        db.execSQL("UPDATE " + AdressDao.TABLENAME + " SET " +
                                AdressDao.Properties.Changed.columnName + "='" + changed.getTime() + ", " +
                                AdressDao.Properties.Created.columnName + "=" + created.getTime() + " ");

                        db.execSQL("UPDATE " + AttendanceDao.TABLENAME + " SET " +
                                AttendanceDao.Properties.Changed.columnName + "='" + changed.getTime() + ", " +
                                AttendanceDao.Properties.Created.columnName + "=" + created.getTime() + " ");

                        db.setTransactionSuccessful();
                    } catch (Exception e) {

                    } finally {
                        db.endTransaction();
                    }
                    break;
            }
        }

    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(PersonDao.class);
        registerDaoClass(ContactDao.class);
        registerDaoClass(AttendanceDao.class);
        registerDaoClass(AdressDao.class);
        registerDaoClass(RelativeDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
