package de.kreth.clubhelper.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import de.kreth.clubhelper.SyncStatus;
import de.kreth.clubhelper.SyncStatus.SyncStatusConverter;

import de.kreth.clubhelper.Group;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP".
*/
public class GroupDao extends AbstractDao<Group, Long> {

    public static final String TABLENAME = "GROUP";

    /**
     * Properties of entity Group.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Changed = new Property(2, java.util.Date.class, "changed", false, "CHANGED");
        public final static Property Created = new Property(3, java.util.Date.class, "created", false, "CREATED");
        public final static Property SyncStatus = new Property(4, Integer.class, "syncStatus", false, "SYNC_STATUS");
    };

    private DaoSession daoSession;

    private final SyncStatusConverter syncStatusConverter = new SyncStatusConverter();
    private Query<Group> personGroup_GroupListQuery;

    public GroupDao(DaoConfig config) {
        super(config);
    }
    
    public GroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT NOT NULL UNIQUE ," + // 1: name
                "\"CHANGED\" INTEGER NOT NULL ," + // 2: changed
                "\"CREATED\" INTEGER NOT NULL ," + // 3: created
                "\"SYNC_STATUS\" INTEGER);"); // 4: syncStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Group entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getChanged().getTime());
        stmt.bindLong(4, entity.getCreated().getTime());
 
        SyncStatus syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindLong(5, syncStatusConverter.convertToDatabaseValue(syncStatus));
        }
    }

    @Override
    protected void attachEntity(Group entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Group readEntity(Cursor cursor, int offset) {
        Group entity = new Group( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            new java.util.Date(cursor.getLong(offset + 2)), // changed
            new java.util.Date(cursor.getLong(offset + 3)), // created
            cursor.isNull(offset + 4) ? null : syncStatusConverter.convertToEntityProperty(cursor.getInt(offset + 4)) // syncStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Group entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setChanged(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setCreated(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setSyncStatus(cursor.isNull(offset + 4) ? null : syncStatusConverter.convertToEntityProperty(cursor.getInt(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Group entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Group entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "groupList" to-many relationship of PersonGroup. */
    public List<Group> _queryPersonGroup_GroupList(Long id) {
        synchronized (this) {
            if (personGroup_GroupListQuery == null) {
                QueryBuilder<Group> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id.eq(null));
                personGroup_GroupListQuery = queryBuilder.build();
            }
        }
        Query<Group> query = personGroup_GroupListQuery.forCurrentThread();
        query.setParameter(0, id);
        return query.list();
    }

}
