package de.kreth.clubhelper.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import de.kreth.clubhelper.SyncStatus;
import de.kreth.clubhelper.SyncStatus.SyncStatusConverter;

import de.kreth.clubhelper.PersonGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERSON_GROUP".
*/
public class PersonGroupDao extends AbstractDao<PersonGroup, Long> {

    public static final String TABLENAME = "PERSON_GROUP";

    /**
     * Properties of entity PersonGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PersonId = new Property(1, long.class, "personId", false, "PERSON_ID");
        public final static Property GroupId = new Property(2, long.class, "groupId", false, "GROUP_ID");
        public final static Property Changed = new Property(3, java.util.Date.class, "changed", false, "CHANGED");
        public final static Property Created = new Property(4, java.util.Date.class, "created", false, "CREATED");
        public final static Property SyncStatus = new Property(5, Integer.class, "syncStatus", false, "SYNC_STATUS");
    };

    private DaoSession daoSession;

    private final SyncStatusConverter syncStatusConverter = new SyncStatusConverter();
    private Query<PersonGroup> person_PersonGroupListQuery;
    private Query<PersonGroup> group_PersonGroupListQuery;

    public PersonGroupDao(DaoConfig config) {
        super(config);
    }
    
    public PersonGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERSON_GROUP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PERSON_ID\" INTEGER NOT NULL ," + // 1: personId
                "\"GROUP_ID\" INTEGER NOT NULL ," + // 2: groupId
                "\"CHANGED\" INTEGER NOT NULL ," + // 3: changed
                "\"CREATED\" INTEGER NOT NULL ," + // 4: created
                "\"SYNC_STATUS\" INTEGER);"); // 5: syncStatus
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "PersonGroupUnique ON PERSON_GROUP" +
                " (\"PERSON_ID\",\"GROUP_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERSON_GROUP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PersonGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPersonId());
        stmt.bindLong(3, entity.getGroupId());
        stmt.bindLong(4, entity.getChanged().getTime());
        stmt.bindLong(5, entity.getCreated().getTime());
 
        SyncStatus syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindLong(6, syncStatusConverter.convertToDatabaseValue(syncStatus));
        }
    }

    @Override
    protected void attachEntity(PersonGroup entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PersonGroup readEntity(Cursor cursor, int offset) {
        PersonGroup entity = new PersonGroup( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // personId
            cursor.getLong(offset + 2), // groupId
            new java.util.Date(cursor.getLong(offset + 3)), // changed
            new java.util.Date(cursor.getLong(offset + 4)), // created
            cursor.isNull(offset + 5) ? null : syncStatusConverter.convertToEntityProperty(cursor.getInt(offset + 5)) // syncStatus
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PersonGroup entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPersonId(cursor.getLong(offset + 1));
        entity.setGroupId(cursor.getLong(offset + 2));
        entity.setChanged(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setCreated(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setSyncStatus(cursor.isNull(offset + 5) ? null : syncStatusConverter.convertToEntityProperty(cursor.getInt(offset + 5)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PersonGroup entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PersonGroup entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "personGroupList" to-many relationship of Person. */
    public List<PersonGroup> _queryPerson_PersonGroupList(long personId) {
        synchronized (this) {
            if (person_PersonGroupListQuery == null) {
                QueryBuilder<PersonGroup> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PersonId.eq(null));
                person_PersonGroupListQuery = queryBuilder.build();
            }
        }
        Query<PersonGroup> query = person_PersonGroupListQuery.forCurrentThread();
        query.setParameter(0, personId);
        return query.list();
    }

    /** Internal query to resolve the "personGroupList" to-many relationship of Group. */
    public List<PersonGroup> _queryGroup_PersonGroupList(long groupId) {
        synchronized (this) {
            if (group_PersonGroupListQuery == null) {
                QueryBuilder<PersonGroup> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GroupId.eq(null));
                group_PersonGroupListQuery = queryBuilder.build();
            }
        }
        Query<PersonGroup> query = group_PersonGroupListQuery.forCurrentThread();
        query.setParameter(0, groupId);
        return query.list();
    }

}
