package de.kreth.clubhelper.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DELETED_ENTRIES".
 */
public class DeletedEntries implements Data {

    private Long id;
    private String tablename;
    private Long entryId;
    /** Not-null value. */
    private java.util.Date changed;
    /** Not-null value. */
    private java.util.Date created;
    private SyncStatus syncStatus;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DeletedEntries() {
    }

    public DeletedEntries(Long id) {
        this.id = id;
    }

    public DeletedEntries(Long id, String tablename, Long entryId, java.util.Date changed, java.util.Date created, SyncStatus syncStatus) {
        this.id = id;
        this.tablename = tablename;
        this.entryId = entryId;
        this.changed = changed;
        this.created = created;
        this.syncStatus = syncStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTablename() {
        return tablename;
    }

    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    public Long getEntryId() {
        return entryId;
    }

    public void setEntryId(Long entryId) {
        this.entryId = entryId;
    }

    /** Not-null value. */
    public java.util.Date getChanged() {
        return changed;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChanged(java.util.Date changed) {
        this.changed = changed;
    }

    /** Not-null value. */
    public java.util.Date getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public SyncStatus getSyncStatus() {
        return syncStatus;
    }

    public void setSyncStatus(SyncStatus syncStatus) {
        this.syncStatus = syncStatus;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
