package de.kreth.clubhelper;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ATTENDANCE.
 */
public class Attendance implements Data, java.io.Serializable {

    private Long id;
    private java.util.Date onDate;
    private long personId;
    /** Not-null value. */
    private java.util.Date changed;
    /** Not-null value. */
    private java.util.Date created;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Attendance() {
    }

    public Attendance(Long id) {
        this.id = id;
    }

    public Attendance(Long id, java.util.Date onDate, long personId, java.util.Date changed, java.util.Date created) {
        this.id = id;
        this.onDate = onDate;
        this.personId = personId;
        this.changed = changed;
        this.created = created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getOnDate() {
        return onDate;
    }

    public void setOnDate(java.util.Date onDate) {
        this.onDate = onDate;
    }

    public long getPersonId() {
        return personId;
    }

    public void setPersonId(long personId) {
        this.personId = personId;
    }

    /** Not-null value. */
    public java.util.Date getChanged() {
        return changed;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChanged(java.util.Date changed) {
        this.changed = changed;
    }

    /** Not-null value. */
    public java.util.Date getCreated() {
        return created;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Attendance that = (Attendance) o;

        if (personId != that.personId) return false;
        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        if (onDate != null ? !onDate.equals(that.onDate) : that.onDate != null) return false;
        if (changed != null ? !changed.equals(that.changed) : that.changed != null) return false;
        return !(created != null ? !created.equals(that.created) : that.created != null);

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (onDate != null ? onDate.hashCode() : 0);
        result = 31 * result + (int) (personId ^ (personId >>> 32));
        result = 31 * result + (changed != null ? changed.hashCode() : 0);
        result = 31 * result + (created != null ? created.hashCode() : 0);
        return result;
    }

    // KEEP METHODS END

}
