package de.kreth.clubhelper;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ATTENDANCE.
 */
public class Attendance {

    private java.util.Date onDate;
    private Long personId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Attendance() {
    }

    public Attendance(java.util.Date onDate, Long personId) {
        this.onDate = onDate;
        this.personId = personId;
    }

    public java.util.Date getOnDate() {
        return onDate;
    }

    public void setOnDate(java.util.Date onDate) {
        this.onDate = onDate;
    }

    public Long getPersonId() {
        return personId;
    }

    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
