package de.kreth.clubhelper;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SYNCHRONIZATION".
 */
public class Synchronization {

    private Long id;
    private String table_name;
    private java.util.Date upload_successful;
    private java.util.Date download_successful;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Synchronization() {
    }

    public Synchronization(Long id) {
        this.id = id;
    }

    public Synchronization(Long id, String table_name, java.util.Date upload_successful, java.util.Date download_successful) {
        this.id = id;
        this.table_name = table_name;
        this.upload_successful = upload_successful;
        this.download_successful = download_successful;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTable_name() {
        return table_name;
    }

    public void setTable_name(String table_name) {
        this.table_name = table_name;
    }

    public java.util.Date getUpload_successful() {
        return upload_successful;
    }

    public void setUpload_successful(java.util.Date upload_successful) {
        this.upload_successful = upload_successful;
    }

    public java.util.Date getDownload_successful() {
        return download_successful;
    }

    public void setDownload_successful(java.util.Date download_successful) {
        this.download_successful = download_successful;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
